openapi: 3.0.0
x-stoplight:
  id: 38f716e8b97ef
info:
  title: Only Once Share
  version: 1.0.1
  description: DHDTech only once secure password sharing.
  contact:
    name: dhdtech customer support
    url: 'https://dhdtech.io'
    email: WeWillHelpYou@dhdtech.io
  termsOfService: 'https://dhdtech.io/terms/'
servers:
  - url: 'http://localhost:6661'
    description: Local Environment
  - url: 'https://api.chamaleon-developer.r2d2skf.com.br/ui'
    description: Developer Environment
  - description: Staging Environment
    url: 'https://api.chamaleon-staging.r2d2skf.com.br/ui'
  - url: 'https://api.chamaleon-production.r2d2skf.com.br/ui'
    description: Production Environment
paths:
  /health:
    get:
      summary: Health
      tags:
        - Infrastructure
      responses:
        '200':
          $ref: '#/components/responses/HealthResponse'
        '412':
          $ref: '#/components/responses/HealthResponse'
      operationId: get-health
      description: Indicates if the service is up and ready to serve requests.
  '/secret/{secret_id}':
    get:
      summary: Secret
      tags:
        - oos
      responses:
        '200':
          $ref: '#/components/responses/GetSecretSuccessResponse'
        '404':
          description: Not found.
      operationId: get-secret-by-id
      description: One time retrieval of a secret by id.
      parameters:
        - $ref: '#/components/parameters/language'
        - $ref: '#/components/parameters/xnxsoss'
    parameters:
      - schema:
          type: string
          format: uuid
          example: 886313e1-3b8a-5372-9b90-0c9aee199e5d
        name: secret_id
        in: path
        required: true
        description: Secrete identification
  /secret/:
    post:
      summary: ''
      operationId: create-secret
      responses:
        '200':
          $ref: '#/components/responses/CreateSecretResponse'
      requestBody:
        $ref: '#/components/requestBodies/CreateSecretRequest'
      parameters:
        - $ref: '#/components/parameters/language'
      tags:
        - oos
  '/locale/{locale}':
    get:
      summary: Internationalization
      tags:
        - oos
      responses:
        '200':
          $ref: '#/components/responses/GetLocaleResponse'
      operationId: get-locale
      description: Return a list of messages acording with the locale provided in path parameter.
    parameters:
      - schema:
          type: string
          enum:
            - pt
            - en
            - es
        name: locale
        in: path
        required: true
components:
  schemas: {}
  securitySchemes: {}
  responses:
    HealthResponse:
      description: Returns dependant's service status
      content:
        application/json:
          schema:
            type: object
            x-examples:
              example-1:
                redis: true
            properties:
              redis:
                type: boolean
                description: Indicate if redis is reachable or not
            required:
              - redis
          examples:
            Redis-OK:
              value:
                redis: true
    GetSecretSuccessResponse:
      description: Will be returned with the secret details.
      content:
        application/json:
          schema:
            type: object
            x-examples:
              example-1:
                secret_id: 886313e1-3b8a-5372-9b90-0c9aee199e5d
                created_at: '2022-01-01 23:00:00'
            properties:
              secret_value:
                type: string
                example: Some sensitive data
                description: The secret value shared.
            required:
              - secret_value
          examples:
            example-1:
              value:
                secret_id: string
                created_at: '2019-08-24T14:15:22Z'
                secret_value: Some sensitive data
    CreateSecretResponse:
      description: Response to a successful created secret.
      content:
        application/json:
          schema:
            type: object
            properties:
              secret_id:
                type: string
                description: Secret identification.
                example: 00910948-0861-446e-935e-624d03266dfd
              recovery_key:
                type: string
                description: Recovery key to decrypt the shared value.
              ttl:
                type: integer
                format: int32
                example: 24
                description: Time to live the secret will be available to decrypt.
            required:
              - secret_id
              - recovery_key
              - ttl
    GetLocaleResponse:
      description: Texts used on UI
      content:
        application/json:
          schema:
            type: object
            properties:
              button_value:
                type: string
              message_click_to_copy_es_es:
                type: string
              message_click_to_copy_pt_br:
                type: string
              message_click_to_copy_us_us:
                type: string
              message_header:
                type: string
              message_header_shared:
                type: string
              message_subheader:
                type: string
              message_subheader_shared:
                type: string
              powered_by:
                type: string
              powered_by_link:
                type: string
            x-examples:
              Example 1:
                button_value: Compartilhe!
                message_click_to_copy_es_es: ¡Haz clic aquí para copiar la URL!
                message_click_to_copy_pt_br: Clique aqui para copiar o link!
                message_click_to_copy_us_us: Click here to copy the shareable url!
                message_header: Compartilhe apenas uma vez!
                message_header_shared: OK! Já criptografamos tudo para você.
                message_subheader: 'Compartilhe com segurança e apenas com uma pessoa, uma vez.'
                message_subheader_shared: Copie o link no idioma de preferência de quem receberá o valor.
                powered_by: Desenvolvido por DHD Tech Solutions
                powered_by_link: 'https://dhdtech.io'
          examples: {}
        application/xml:
          schema:
            type: object
            properties:
              button_value:
                type: string
              message_click_to_copy_es_es:
                type: string
              message_click_to_copy_pt_br:
                type: string
              message_click_to_copy_us_us:
                type: string
              message_header:
                type: string
              message_header_shared:
                type: string
              message_subheader:
                type: string
              message_subheader_shared:
                type: string
              powered_by:
                type: string
              powered_by_link:
                type: string
            x-examples:
              Example 1:
                button_value: Compartilhe!
                message_click_to_copy_es_es: ¡Haz clic aquí para copiar la URL!
                message_click_to_copy_pt_br: Clique aqui para copiar o link!
                message_click_to_copy_us_us: Click here to copy the shareable url!
                message_header: Compartilhe apenas uma vez!
                message_header_shared: OK! Já criptografamos tudo para você.
                message_subheader: 'Compartilhe com segurança e apenas com uma pessoa, uma vez.'
                message_subheader_shared: Copie o link no idioma de preferência de quem  receberá o valor.
                powered_by: Desenvolvido por DHD Tech Solutions
                powered_by_link: 'https://dhdtech.io'
  requestBodies:
    CreateSecretRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              secret_value:
                type: string
                example: Any string to be shared securely
                description: Represents the value to be shared securely.
            required:
              - secret_value
          examples:
            Example 001:
              value:
                secret_value: Any string to be shared securely
      description: Body specification to create a secret.
  parameters:
    language:
      name: locale
      in: query
      required: true
      schema:
        type: string
        enum:
          - pt
          - es
          - en
        example: pt
      description: Define language to be used.
    xnxsoss:
      name: xnxsoss
      in: query
      required: true
      schema:
        type: string
      description: Base64 encoded decrypt key
tags:
  - name: Infrastructure
  - name: oos
