name: Build Docker, and publish to Production K8s
on:
  push:
    branches: [ main ]
jobs:
    deploy:
      name: Upload to Amazon S3
      runs-on: ubuntu-latest
      # These permissions are needed to interact with GitHub's OIDC Token endpoint.
      permissions:
        id-token: write
        contents: read
      steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      # - name: Configure AWS credentials from Test account
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: arn:aws:iam::683573524234:role/dhd-tech-github-actions-oidc
      #     aws-region: us-east-1
      # - name: Build and push Docker image
      #   uses: dhdtech/aws-ecr-action@master
      #   with:
      #       account_id:  ${{ secrets.DHDTECH_ACCOUNT_ID }}
      #       repo: oos-share
      #       create_repo: true
      #       region: us-east-1
      #       tags: ${{ env.BRANCH }}          
      - name: Apply  deployment
        uses: dhdtech/eks-kubectl-action@master
        with:
          aws_region: us-east-1
          cluster_name: dhdtech-dev-use1
          args: apply -f deploy/deployApplication-${{ env.BRANCH }}.yaml
      # - name: Restart deployment
      #   uses: ianbelcher/eks-kubectl-action@master
      #   with:
      #     aws_region: us-east-1
      #     cluster_name: dhdtech-dev-use1
      #     args: rollout restart deployment/oos-share -n oos-share            